### ISSUE TITLE
Is this a fork of Ouroboros?

### ISSUE THREAD

**Issue by nemchik** [docupdater/docupdater#11]
https://github.com/pyouroboros/ouroboros

Seems really similar, what makes this different?

**Comment by davidgrieser** [comment]
Seems like it was forked 3af13e9b9f791c3dc6809230622d74c0e20d5f10. Not sure why though. I would think you'd want to join an existing project than maintain your own, but maybe there is some reason.

**Comment by mathcantin** [comment]
Yes, it is. I realize that I only mention it in the release notes. I will fix that mistake.

At first I wanted to contribute to Ouroboros. Essentially I needed 4 new features:
1. Turn off the startup notification
2. Override notifications by containers/services
3. Customize the notification message
4. A webhook to pause/resume update

My pull request cover point 1, 2 and 3. The owner team rejected this because that don't fit in theirs visions. That's okay because it is about their rights as owner. In reality the Oroborous project is more like a open source software by a close team, the main team protects every lines of her code from outside update.

The project required many other modifications, the documentation is outdated, no units tests, architecture is bad... And I still need my few features. I just decided to fork the project and to share it.

Docupdater will not follow Oroborous update. This is now a full independent project. Maybe it will have more or less features than Oroborous, I don't care. This project has is own set of features, I will continually updated it, I will accept any comments or pull request that match with the project.

**Comment by nemchik** [comment]
Neat.
